# Generated by Django 2.1.4 on 2019-03-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='dataposted',
            new_name='dateposted',
        ),
    ]
